import chalk from 'chalk';

export async function helpCommand(): Promise<void> {
  console.log();
  console.log(chalk.bold('Hop - An extensible port proxy + request enhancement CLI tool'));
  console.log();
  console.log(chalk.bold('USAGE:'));
  console.log('  hop <command> [options]');
  console.log();
  console.log(chalk.bold('COMMANDS:'));
  console.log(`  ${chalk.cyan('add')}              Add a new proxy rule (interactive)`);
  console.log(`  ${chalk.cyan('list, ls')}         List all configured proxies`);
  console.log(`  ${chalk.cyan('edit')}             Edit an existing proxy rule (interactive)`);
  console.log(`  ${chalk.cyan('remove, rm')}       Remove a proxy rule (interactive)`);
  console.log(`  ${chalk.cyan('serve [names...]')} Start proxy servers (all or specific ones)`);
  console.log(`  ${chalk.cyan('help')}             Display this help information`);
  console.log();
  console.log(chalk.bold('EXAMPLES:'));
  console.log(`  ${chalk.gray('# Add a new proxy')}`);
  console.log(`  $ hop add`);
  console.log();
  console.log(`  ${chalk.gray('# List all proxies')}`);
  console.log(`  $ hop list`);
  console.log();
  console.log(`  ${chalk.gray('# Edit a proxy')}`);
  console.log(`  $ hop edit`);
  console.log();
  console.log(`  ${chalk.gray('# Start all proxies')}`);
  console.log(`  $ hop serve`);
  console.log();
  console.log(`  ${chalk.gray('# Start specific proxies by name')}`);
  console.log(`  $ hop serve api-proxy auth-service`);
  console.log();
  console.log(`  ${chalk.gray('# Remove a proxy')}`);
  console.log(`  $ hop remove`);
  console.log();
  console.log(chalk.bold('PATH MATCHING:'));
  console.log('  When adding a proxy, you can specify paths to match (comma-separated).');
  console.log('  If no paths are specified, all requests will be proxied.');
  console.log();
  console.log(`  ${chalk.gray('Example paths: /api/users, /api/posts, /v1/auth')}`);
  console.log();
  console.log(chalk.bold('CONFIGURATION:'));
  console.log(`  Config file location: ${chalk.yellow('~/.hop/config.json')}`);
  console.log();
  console.log(chalk.bold('MORE INFO:'));
  console.log('  Use --help flag with any command for more details');
  console.log(`  ${chalk.gray('Example:')} hop serve --help`);
  console.log();
}
